### ISSUE TITLE
似乎连不上

### ISSUE THREAD

**Issue by funte** [sxbai/ss-on-replit#1]
原项目默认使用 8488, 但我用 telnet 试了下这个端口连不上
![image](https://user-images.githubusercontent.com/9884836/208359107-86e07c50-b30f-4338-abef-f9a661dbf4ca.png)
![image](https://user-images.githubusercontent.com/9884836/208359165-fc27bcda-d85d-4c9f-8d8a-5e664a7d9aae.png)

**Comment by sxbai** [comment]
不推荐直接使用ss-replit的项目名搭建，可以随意设置，端口一般443
